# EladerWand Api

# user login
POST {{HOST}}/api/login
Accept: application/json
Content-Type: application/json

{
    "username": "{{USERNAME}}",
    "password": "{{PASSWORD}}"
}

###


# Get service info
GET {{HOST}}/api/info
Authorization: Bearer {{AUTH_TOKEN}}

###


# List source projects
GET {{HOST}}/api/migration/projects?dbname={{MIGRATION_MONGODB_SAKE}}&conn={{MIGRATION_MONGODB_URI}}&version=200
Accept: application/json
Content-type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

###


# List source spaces
GET {{HOST}}/api/migration/projects/{{MIGRATION_TARGET_PROJECT_CODE}}/spaces?dbname={{MIGRATION_MONGODB_SAKE}}&conn={{MIGRATION_MONGODB_URI}}&version=200
Accept: application/json
Content-type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

###


# List source devices
GET {{HOST}}/api/migration/projects/{{MIGRATION_TARGET_PROJECT_CODE}}/devices?dbname={{MIGRATION_MONGODB_SAKE}}&conn={{MIGRATION_MONGODB_URI}}&version=200
Accept: application/json
Content-type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

###


# List source device template by project
GET {{HOST}}/api/migration/device/templates?dbname={{MIGRATION_MONGODB_THINGS}}&conn={{MIGRATION_MONGODB_URI}}&version=200
Accept: application/json
Authorization: Bearer {{AUTH_TOKEN}}

###


# Import device templates
POST {{HOST}}/api/migration/device/templates?dbname={{MIGRATION_MONGODB_THINGS}}&conn={{MIGRATION_MONGODB_URI}}&version=200
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

{}

###


# Import devices
POST {{HOST}}/api/migration/projects/{{MIGRATION_TARGET_PROJECT_CODE}}/devices?dbname={{MIGRATION_MONGODB_SAKE}}&conn={{MIGRATION_MONGODB_URI}}&version=200
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

###


# Import devices with new project code
POST {{HOST}}/api/migration/projects/{{MIGRATION_TARGET_PROJECT_CODE}}/devices?dbname={{MIGRATION_MONGODB_SAKE}}&conn={{MIGRATION_MONGODB_URI}}&version=200
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

{
    "code": "{{TARGET_PROJECT_CODE}}"
}

###


// gateway connect
PUT {{HOST}}/api/gateway/connections
Accept: application/json
Content-Type: application/json

//  "id": "1a6a908e-3bdf-49a5-82a3-1258347adfb0",
{
  "publicIP": "{{CLIENT_IP}}",
  "traceIP": "192.168.0.1,{{CLIENT_IP}}",
  "networkCards": [
    {
      "enable": true,
      "ip": "192.168.0.102",
      "name": "eth0",
      "network": "internet",
      "mac": "55:00:21:33:66:33"
    },
    {
      "enable": true,
      "ip": "172.168.31.99",
      "name": "eth1",
      "network": "intranet",
      "mac": "44:00:21:33:66:11"
    }
  ],
  "swInfos": {
    "ADHardKeySun": "0.0.0.1",
    "ADModbusSun": "1.0.6.1",
    "SationKNXSun": "0.0.0.1",
    "driftice": "3.0.17",
    "image": "0.3",
    "libadmodbus": "2.0.5.2",
    "sun": "1.1.5.0"
  }
}

###


# List gateway connections
GET {{HOST}}/api/gateway/connections?clientIP={{CLIENT_IP}}
Accept: application/json
Content-Type: application/json

###

// List devices
GET {{HOST}}/api/devices?projectId={{TARGET_PROJECT_CODE}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

###


// Get device
GET {{HOST}}/api/devices/{{TARGET_DEVICE_ID}}?projectId={{TARGET_PROJECT_CODE}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

###


// Get device by DvID
GET {{HOST}}/api/devices/{{TARGET_DEVICE_DVID}}?projectId={{TARGET_PROJECT_CODE}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

###


// Bind the Gateway connection To the device
PUT {{HOST}}/api/devices/{{TARGET_DEVICE_DVID}}/gateway?projectId={{TARGET_PROJECT_CODE}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

{
    "cid": "{{GATEWAY_CONNECTION_ID}}"
}

###


// UnBind the Gateway connection To the device
DELETE {{HOST}}/api/devices/{{TARGET_DEVICE_DVID}}/gateway?projectId={{TARGET_PROJECT_CODE}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

{}

###


// Get device repository
GET {{HOST}}/api/devices/{{TARGET_DEVICE_DVID}}/repository?projectId={{TARGET_PROJECT_CODE}}
Accept: application/json
Content-Type: application/json

###


// Get device repository from version2
GET {{HOST}}/api/v2/devices/{{TARGET_DEVICE_DVID}}/repository?projectId={{TARGET_PROJECT_CODE}}
Accept: application/json
Content-Type: application/json

###


// TEMP
# Import devices
POST {{HOST}}/api/migration/projects/{{MIGRATION_TARGET_PROJECT_CODE}}/devices?dbname={{MIGRATION_MONGODB_SAKE}}&conn={{MIGRATION_MONGODB_URI}}&version=200
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

###


// List devices
GET {{HOST}}/api/devices?projectId={{TARGET_PROJECT_CODE}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}
