# api get example
GET {{HOST}}/api/example
Accept: application/json
Authorization: Bearer {{AUTH_TOKEN}}

###


# list source projects
GET {{HOST}}/api/migration/projects?dbname={{MIGRATION_MONGODB_SAKE}}&conn={{MIGRATION_MONGODB_URI}}&version=200
Accept: application/json
Content-type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

###


# get the source project
GET {{HOST}}/api/migration/projects/{{MIGRATION_TARGET_PROJECT_CODE}}?dbname={{MIGRATION_MONGODB_SAKE}}&conn={{MIGRATION_MONGODB_URI}}&version=200
Accept: application/json
Content-type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

###


# list source projects to be 400
GET {{HOST}}/api/migration/projects
Accept: application/json
Content-type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

###


# list source spaces
GET {{HOST}}/api/migration/projects/{{MIGRATION_TARGET_PROJECT_CODE}}/spaces?dbname={{MIGRATION_MONGODB_SAKE}}&conn={{MIGRATION_MONGODB_URI}}&version=200
Accept: application/json
Content-type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

###


# list source devices
GET {{HOST}}/api/migration/projects/{{MIGRATION_TARGET_PROJECT_CODE}}/devices?dbname={{MIGRATION_MONGODB_SAKE}}&conn={{MIGRATION_MONGODB_URI}}&version=200
Accept: application/json
Content-type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

###


# List source device template by project
GET {{HOST}}/api/migration/device/templates?dbname={{MIGRATION_MONGODB_THINGS}}&conn={{MIGRATION_MONGODB_URI}}&version=200
accept: application/json
Authorization: Bearer {{AUTH_TOKEN}}

###


# Import device templates
POST {{HOST}}/api/migration/device/templates?dbname={{MIGRATION_MONGODB_THINGS}}&conn={{MIGRATION_MONGODB_URI}}&version=200
accept: application/json
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

{}

###


# Import project
POST {{HOST}}/api/migration/projects/{{MIGRATION_TARGET_PROJECT_CODE}}?dbname={{MIGRATION_MONGODB_SAKE}}&conn={{MIGRATION_MONGODB_URI}}&version=200
accept: application/json
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

###


# Import project with new project code
POST {{HOST}}/api/migration/projects/{{MIGRATION_TARGET_PROJECT_CODE}}?dbname={{MIGRATION_MONGODB_SAKE}}&conn={{MIGRATION_MONGODB_URI}}&version=200
accept: application/json
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

{
    "code": "TEST"
}

###



# Import spaces
POST {{HOST}}/api/migration/projects/{{MIGRATION_TARGET_PROJECT_CODE}}/spaces?dbname={{MIGRATION_MONGODB_SAKE}}&conn={{MIGRATION_MONGODB_URI}}&version=200
accept: application/json
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

###



# Import devices
POST {{HOST}}/api/migration/projects/{{MIGRATION_TARGET_PROJECT_CODE}}/devices?dbname={{MIGRATION_MONGODB_SAKE}}&conn={{MIGRATION_MONGODB_URI}}&version=200
accept: application/json
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

###



# Import devices with new project code
POST {{HOST}}/api/migration/projects/{{MIGRATION_TARGET_PROJECT_CODE}}/devices?dbname={{MIGRATION_MONGODB_SAKE}}&conn={{MIGRATION_MONGODB_URI}}&version=200
accept: application/json
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

{
    "code": "{{TARGET_PROJECT_CODE}}"
}

###
