# feathc projects
GET {{HOST}}/api/projects
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

###

# list spaces by project
GET {{HOST}}/api/spaces?projectId={{TARGET_PROJECT_CODE}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

###


# get the space
GET {{HOST}}/api/spaces/{{TARGET_SPACE_ID}}?projectId={{TARGET_PROJECT_CODE}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

###


# get the space topology
GET {{HOST}}/api/spaces/{{TARGET_SPACE_ID}}/topology?projectId={{TARGET_PROJECT_CODE}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

###

