import DeviceHelper from '../DeviceHelper';
import DeviceVM from '../DeviceVMs';

describe('Parse Flags', () => {
    test('should be successful', async () => {
        const helper = new DeviceHelper({ device: actuator });

        const { isActuator } = helper.isActuator();

        actuator.attrs.map((attr: { objId: number; flags: number }) => {
            const flags = (!attr?.flags ? 0 : attr?.flags)
                .toString(2)
                .padStart(8, '0');

            const rule = DeviceHelper.parseFlagRule(
                !attr.flags ? 0 : attr.flags
            );
            console.log({ str: flags, objId: attr.objId, rule });
        });
    });
});

const actuator: DeviceVM = {
    id: '4faa9f45-9cfa-4ddf-8c1a-2ef0015a1af0',
    name: '继电器4路10A',
    dvId: 'GOLD-MQx0pTghhaSX',
    typeId: 60930,
    type: {
        id: 60930,
        name: 'LightActuator',
        categoryId: 'A',
        category: {
            id: 'A',
            name: 'Actuator',
        },
    },
    modelId: '2e213f1f-2532-459e-932b-a95befc06223',
    model: {
        id: '2e213f1f-2532-459e-932b-a95befc06223',
        name: 'M/R4.10.1',
        brandId: '32ecb2e6-7d95-4e36-8add-cbd671cc2644',
        brand: {
            id: '32ecb2e6-7d95-4e36-8add-cbd671cc2644',
            code: 'HDL',
            name: 'HDL',
        },
    },
    projectId: '57eb360a-5897-4f15-8f65-12758d2d16d5',
    spaceId: '59fcadb1-b64e-4a15-af56-1207896bad6b',
    parentId: 'b5778e9f-2a71-4495-bd53-3ebcd36ac35a',
    iconId: 'b538e321-8421-41b5-bc94-06a8f8bd4b44',
    icon: {
        id: 'b538e321-8421-41b5-bc94-06a8f8bd4b44',
        name: 'Structure',
        path: 'c-2.png',
        tags: ['system'],
    },
    images: [
        {
            id: '54619d6a-b354-48e8-8223-3513427bb5ae',
            name: 'HDL_M-R4.10.1',
            path: 'HDL_M-R4.10.1.png',
            tags: ['system'],
        },
    ],
    protocols: [
        {
            id: 'fe15f821-87d6-404f-a97c-df4b8db022d9',
            typeId: 'KNX',
            type: {
                id: 'KNX',
                name: 'KNX',
            },
            commInfo: {
                objs: [
                    {
                        ch: 1,
                        gAddrs: ['0/0/1'],
                        objId: 1,
                    },
                    {
                        ch: 1,
                        gAddrs: ['0/0/5'],
                        objId: 2,
                    },
                    {
                        ch: 2,
                        gAddrs: ['0/0/2'],
                        objId: 3,
                    },
                    {
                        ch: 2,
                        gAddrs: ['0/0/6'],
                        objId: 4,
                    },
                    {
                        ch: 3,
                        gAddrs: ['0/0/3'],
                        objId: 5,
                    },
                    {
                        ch: 3,
                        gAddrs: ['0/0/7'],
                        objId: 6,
                    },
                    {
                        ch: 4,
                        gAddrs: ['0/0/4'],
                        objId: 7,
                    },
                    {
                        ch: 4,
                        gAddrs: ['0/0/8'],
                        objId: 8,
                    },
                    {
                        attrObjId: 9,
                        ebtn: true,
                        gAddrs: ['0/0/100'],
                        objId: 9,
                    },
                ],
                pAddr: '1.1.11',
            },
        },
    ],
    specId: '7936f0d9-0665-4e73-b9e4-a11e9e1d2564',
    spec: {
        id: '7936f0d9-0665-4e73-b9e4-a11e9e1d2564',
        // manufacturerCode: null,
        switchPanel: null,
        KNX: null,
        RS485: null,
        // EEPCode: null,
        EnOcean: {
            EEPCode: null,
        },
    },
    channelInfo: [
        {
            channelNo: 1,
            dvId: 'GOLD-QuLpQpcKEtEt',
        },
        {
            channelNo: 2,
            dvId: 'GOLD-9wKGvmmNEY0I',
        },
        {
            channelNo: 3,
            dvId: 'GOLD-ncU5lmD3fWrr',
        },
        {
            channelNo: 4,
            dvId: 'GOLD-V87itIZpPEcz',
        },
    ],
    switchPanelControlInfo: null,
    attrs: [
        {
            Name_zh_CN: '开关',
            chId: 1,
            createdRT: 'oic.r.switch.binary',
            dpt: '1.001',
            flags: 148,
            funId: 'Switch',
            name: '开关',
            objId: 1,
            rt: ['bh.r.attr.actuator'],
            valueKey: 'value',
            valueType: 'boolean',
        },
        {
            Name_zh_CN: '开关',
            ack4Obj: 1,
            ackSet: true,
            chId: 1,
            createdRT: 'oic.r.switch.binary',
            dpt: '1.001',
            flags: 76,
            funId: 'Switch',
            name: '开关 状态',
            objId: 2,
            rt: ['bh.r.attr.actuator'],
            valueKey: 'value',
            valueType: 'boolean',
        },
        {
            Name_zh_CN: '开关',
            chId: 2,
            createdRT: 'oic.r.switch.binary',
            dpt: '1.001',
            flags: 148,
            funId: 'Switch',
            name: '开关',
            objId: 3,
            rt: ['bh.r.attr.actuator'],
            valueKey: 'value',
            valueType: 'boolean',
        },
        {
            Name_zh_CN: '开关',
            ack4Obj: 3,
            ackSet: true,
            chId: 2,
            createdRT: 'oic.r.switch.binary',
            dpt: '1.001',
            flags: 76,
            funId: 'Switch',
            name: '开关 状态',
            objId: 4,
            rt: ['bh.r.attr.actuator'],
            valueKey: 'value',
            valueType: 'boolean',
        },
        {
            Name_zh_CN: '开关',
            chId: 3,
            createdRT: 'oic.r.switch.binary',
            dpt: '1.001',
            flags: 148,
            funId: 'Switch',
            name: '开关',
            objId: 5,
            rt: ['bh.r.attr.actuator'],
            valueKey: 'value',
            valueType: 'boolean',
        },
        {
            Name_zh_CN: '开关',
            ack4Obj: 5,
            ackSet: true,
            chId: 3,
            createdRT: 'oic.r.switch.binary',
            dpt: '1.001',
            flags: 76,
            funId: 'Switch',
            name: '开关 状态',
            objId: 6,
            rt: ['bh.r.attr.actuator'],
            valueKey: 'value',
            valueType: 'boolean',
        },
        {
            Name_zh_CN: '开关',
            chId: 4,
            createdRT: 'oic.r.switch.binary',
            dpt: '1.001',
            flags: 148,
            funId: 'Switch',
            name: '开关',
            objId: 7,
            rt: ['bh.r.attr.actuator'],
            valueKey: 'value',
            valueType: 'boolean',
        },
        {
            Name_zh_CN: '开关',
            ack4Obj: 7,
            ackSet: true,
            chId: 4,
            createdRT: 'oic.r.switch.binary',
            dpt: '1.001',
            flags: 76,
            funId: 'Switch',
            name: '开关 状态',
            objId: 8,
            rt: ['bh.r.attr.actuator'],
            valueKey: 'value',
            valueType: 'boolean',
        },
        {
            Name_zh_CN: '心跳',
            appHidden: true,
            createdRT: 'bh.r.dvHeartbeat',
            dpt: '1.006',
            ebtn: true,
            flags: 196,
            funId: 'Heartbeat',
            name: '心跳',
            objId: 9,
            rt: ['bh.r.attr.actuator'],
            suffix: '',
            valueKey: 'value',
            valueType: 'boolean',
        },
    ],
    heartbeat: 60,
    sendTelRules: [2, 4, 6, 8, 9],
    imei: '',
    publicIP: '',
    traceIP: '',
    createdBy: 'd07bf909-3157-4cbe-8661-91ba102aa2ea',
    updatedBy: 'd07bf909-3157-4cbe-8661-91ba102aa2ea',
    createdAt: 1630645484346,
    updatedAt: 1630645484353,
    parent: {
        id: 'b5778e9f-2a71-4495-bd53-3ebcd36ac35a',
        name: 'AltairIoT网关2',
        dvId: 'GOLD-XGqknx0HoRRp',
        typeId: 61184,
        type: {
            id: 61184,
            name: 'IoTGateway',
            categoryId: 'GW',
            category: {
                id: 'GW',
                name: 'Gateway',
            },
        },
        modelId: '30cc6654-8964-476b-b242-e5b770c282f8',
        model: {
            id: '30cc6654-8964-476b-b242-e5b770c282f8',
            name: 'ADM-S2-K1M4',
            brandId: '27f710f4-bab0-4418-b415-7d526a243482',
            brand: {
                id: '27f710f4-bab0-4418-b415-7d526a243482',
                code: 'AdvancedDevices',
                name: 'AdvancedDevices',
            },
        },
        projectId: '57eb360a-5897-4f15-8f65-12758d2d16d5',
        spaceId: '8221abc4-9fc1-42ec-85be-005f93bc35a5',
        iconId: 'a23d4163-249c-439c-9998-ac08772fdeec',
        icon: {
            id: 'a23d4163-249c-439c-9998-ac08772fdeec',
            name: 'AGateway',
            path: 'g-1.png',
            tags: ['system'],
        },
        protocols: [
            {
                id: 'f273fefb-2835-4623-8efc-8d2e02f1831c',
                typeId: 'EtN',
                type: {
                    id: 'EtN',
                    name: 'Ethernet',
                },
            },
            {
                id: '094d1259-fadb-4c90-9d72-b3824f932721',
                typeId: 'MdB',
                type: {
                    id: 'MdB',
                    name: 'Modbus',
                },
            },
            {
                id: '4e74b121-07ff-48bb-9d15-235ea6a2d905',
                typeId: 'KNX',
                type: {
                    id: 'KNX',
                    name: 'KNX',
                },
                commInfo: {
                    UPDs: [
                        {
                            enableIpTunneling: true,
                            ip: '192.168.0.101',
                            name: 'eth0',
                            obtainIpType: 12,
                            port: 3671,
                            type: 'unicast',
                        },
                    ],
                    filters: [
                        {
                            in: '',
                            networkName: 'TP',
                            out: '',
                        },
                        {
                            in: '',
                            networkName: 'eth0',
                            out: '',
                        },
                    ],
                    pAddr: '1.1.1',
                },
            },
        ],
        specId: 'aee7a6d1-1f1a-469a-9d52-87ee4b71e599',
        spec: {
            id: 'aee7a6d1-1f1a-469a-9d52-87ee4b71e599',
            comPortCount: 4,
            networkCardCount: 1,
            // manufacturerCode: null,
            switchPanel: null,
            KNX: null,
            RS485: null,
            EEPCode: null,
        },
        channelInfo: null,
        switchPanelControlInfo: null,
        // attrs: '',
        softwareInfo: [
            {
                name: 'comet',
            },
            {
                name: 'sun',
                version: '1.3.2.2',
            },
            {
                name: 'ADModbusSun',
                version: '1.0.6.1',
            },
            {
                name: 'SationKNXSun',
                version: '1.0.0.1',
            },
            {
                name: 'driftice',
                version: '3.1.9',
            },
            {
                name: 'image',
                version: '0.3',
            },
            {
                name: 'libadmodbus',
                version: '2.0.5.2',
            },
            {
                name: 'package',
                version: '2.0.0.0',
            },
        ],
        imei: '00:00:21:33:66:88',
        publicIP: '114.34.165.180',
        traceIP: '192.168.0.1,114.34.165.180',
        networkCards: [
            {
                id: 'e0a76464-a6f1-4b8c-b8bf-5e30fdd8d177',
                name: 'eth0',
                enable: true,
                ip: '192.168.0.102',
                mac: '00:00:21:33:66:88',
                network: 'internet',
                // createdBy: 'd07bf909-3157-4cbe-8661-91ba102aa2ea',
                // ?updatedBy: 'd07bf909-3157-4cbe-8661-91ba102aa2ea',
                // createdAt: 1630645484159,
                // updatedAt: 1630645484164,
            },
        ],
        createdBy: 'd07bf909-3157-4cbe-8661-91ba102aa2ea',
        updatedBy: 'd07bf909-3157-4cbe-8661-91ba102aa2ea',
        createdAt: 1630645484156,
        updatedAt: 1630645484161,
    } as any,
    leaves: [
        {
            id: '9dbb6185-4bc2-4c5a-b8c9-5d5e8023d556',
            name: '灯3',
            dvId: 'GOLD-ncU5lmD3fWrr',
            typeId: 265,
            type: {
                id: 265,
                name: 'Light',
                categoryId: 'S',
                category: {
                    id: 'S',
                    name: 'SensorAndGeneralDevice',
                },
            },
            modelId: '798da359-c5c8-480d-a5fa-4196b0dbb229',
            model: {
                id: '798da359-c5c8-480d-a5fa-4196b0dbb229',
                name: 'Non',
                brandId: 'ec08a810-8617-49bd-a870-729640d1cbce',
                brand: {
                    id: 'ec08a810-8617-49bd-a870-729640d1cbce',
                    code: 'None',
                    name: 'None',
                },
            },
            projectId: '57eb360a-5897-4f15-8f65-12758d2d16d5',
            spaceId: '59fcadb1-b64e-4a15-af56-1207896bad6b',
            parentId: '4faa9f45-9cfa-4ddf-8c1a-2ef0015a1af0',
            iconId: 'b58f61a7-aff2-403f-a04d-71ab4325cb8c',
            icon: {
                id: 'b58f61a7-aff2-403f-a04d-71ab4325cb8c',
                name: 'ALamp',
                path: 'd-41.png',
                tags: ['system'],
            },
            protocols: [
                {
                    id: 'ef47c051-4734-42a6-9932-94073948e004',
                    typeId: 'KNX',
                    type: {
                        id: 'KNX',
                        name: 'KNX',
                    },
                    commInfo: {
                        objs: [
                            {
                                ch: 3,
                                gAddrs: ['0/0/3'],
                                objId: 1,
                            },
                            {
                                ch: 3,
                                gAddrs: ['0/0/7'],
                                objId: 2,
                            },
                        ],
                        pAddr: '1.1.11',
                    },
                },
            ],
            specId: '363d170a-06a4-4834-91bc-89b5ebe4ec52',
            spec: {
                id: '363d170a-06a4-4834-91bc-89b5ebe4ec52',
                // manufacturerCode: null,
                switchPanel: null,
                KNX: null,
                RS485: null,
                EnOcean: {
                    EEPCode: null,
                },
            },
            channelInfo: null,
            switchPanelControlInfo: null,
            attrs: [
                {
                    Name_zh_CN: '开关',
                    chId: 3,
                    createdRT: 'oic.r.switch.binary',
                    dpt: '1.001',
                    flags: 148,
                    funId: 'Switch',
                    name: '开关',
                    objId: 1,
                    rt: ['bh.r.attr.actuator'],
                    valueKey: 'value',
                    valueType: 'boolean',
                },
                {
                    Name_zh_CN: '开关',
                    ack4Obj: 1,
                    ackSet: true,
                    chId: 3,
                    createdRT: 'oic.r.switch.binary',
                    dpt: '1.001',
                    flags: 76,
                    funId: 'Switch',
                    name: '开关 状态',
                    objId: 2,
                    rt: ['bh.r.attr.actuator'],
                    valueKey: 'value',
                    valueType: 'boolean',
                },
            ],
            heartbeat: 60,
            sendTelRules: [2],
            imei: '',
            publicIP: '',
            traceIP: '',
            createdBy: 'd07bf909-3157-4cbe-8661-91ba102aa2ea',
            updatedBy: 'd07bf909-3157-4cbe-8661-91ba102aa2ea',
            createdAt: 1630645484246,
            updatedAt: 1630645484250,
        },
        {
            id: 'd86db3c2-3d7d-4d9b-be9e-b73a0ff56aa0',
            name: '灯2',
            dvId: 'GOLD-9wKGvmmNEY0I',
            typeId: 265,
            type: {
                id: 265,
                name: 'Light',
                categoryId: 'S',
                category: {
                    id: 'S',
                    name: 'SensorAndGeneralDevice',
                },
            },
            modelId: '798da359-c5c8-480d-a5fa-4196b0dbb229',
            model: {
                id: '798da359-c5c8-480d-a5fa-4196b0dbb229',
                name: 'Non',
                brandId: 'ec08a810-8617-49bd-a870-729640d1cbce',
                brand: {
                    id: 'ec08a810-8617-49bd-a870-729640d1cbce',
                    code: 'None',
                    name: 'None',
                },
            },
            projectId: '57eb360a-5897-4f15-8f65-12758d2d16d5',
            spaceId: '59fcadb1-b64e-4a15-af56-1207896bad6b',
            parentId: '4faa9f45-9cfa-4ddf-8c1a-2ef0015a1af0',
            iconId: 'b58f61a7-aff2-403f-a04d-71ab4325cb8c',
            icon: {
                id: 'b58f61a7-aff2-403f-a04d-71ab4325cb8c',
                name: 'ALamp',
                path: 'd-41.png',
                tags: ['system'],
            },
            protocols: [
                {
                    id: '8c450600-aec7-4d3e-a9d9-70b84d3ff677',
                    typeId: 'KNX',
                    type: {
                        id: 'KNX',
                        name: 'KNX',
                    },
                    commInfo: {
                        objs: [
                            {
                                ch: 2,
                                gAddrs: ['0/0/2'],
                                objId: 1,
                            },
                            {
                                ch: 2,
                                gAddrs: ['0/0/6'],
                                objId: 2,
                            },
                        ],
                        pAddr: '1.1.11',
                    },
                },
            ],
            specId: 'b7238795-1428-4d87-8e79-7b2b015f62bc',
            spec: {
                id: 'b7238795-1428-4d87-8e79-7b2b015f62bc',
                // manufacturerCode: null,
                switchPanel: null,
                KNX: null,
                RS485: null,
                EnOcean: {
                    EEPCode: null,
                },
            },
            channelInfo: null,
            switchPanelControlInfo: null,
            attrs: [
                {
                    Name_zh_CN: '开关',
                    chId: 2,
                    createdRT: 'oic.r.switch.binary',
                    dpt: '1.001',
                    flags: 148,
                    funId: 'Switch',
                    name: '开关',
                    objId: 1,
                    rt: ['bh.r.attr.actuator'],
                    valueKey: 'value',
                    valueType: 'boolean',
                },
                {
                    Name_zh_CN: '开关',
                    ack4Obj: 1,
                    ackSet: true,
                    chId: 2,
                    createdRT: 'oic.r.switch.binary',
                    dpt: '1.001',
                    flags: 76,
                    funId: 'Switch',
                    name: '开关 状态',
                    objId: 2,
                    rt: ['bh.r.attr.actuator'],
                    valueKey: 'value',
                    valueType: 'boolean',
                },
            ],
            heartbeat: 60,
            sendTelRules: [2],
            imei: '',
            publicIP: '',
            traceIP: '',
            createdBy: 'd07bf909-3157-4cbe-8661-91ba102aa2ea',
            updatedBy: 'd07bf909-3157-4cbe-8661-91ba102aa2ea',
            createdAt: 1630645483959,
            updatedAt: 1630645483961,
        },
        {
            id: '02eb8d9a-16a0-4fd7-a739-4e4fbc9d26df',
            name: '灯4',
            dvId: 'GOLD-V87itIZpPEcz',
            typeId: 265,
            type: {
                id: 265,
                name: 'Light',
                categoryId: 'S',
                category: {
                    id: 'S',
                    name: 'SensorAndGeneralDevice',
                },
            },
            modelId: '9c95ad62-7b1e-4920-9d09-3d613daf90f0',
            model: {
                id: '9c95ad62-7b1e-4920-9d09-3d613daf90f0',
                name: 'Non',
                brandId: 'ec08a810-8617-49bd-a870-729640d1cbce',
                brand: {
                    id: 'ec08a810-8617-49bd-a870-729640d1cbce',
                    code: 'None',
                    name: 'None',
                },
            },
            projectId: '57eb360a-5897-4f15-8f65-12758d2d16d5',
            spaceId: '59fcadb1-b64e-4a15-af56-1207896bad6b',
            parentId: '4faa9f45-9cfa-4ddf-8c1a-2ef0015a1af0',
            iconId: 'b58f61a7-aff2-403f-a04d-71ab4325cb8c',
            icon: {
                id: 'b58f61a7-aff2-403f-a04d-71ab4325cb8c',
                name: 'ALamp',
                path: 'd-41.png',
                tags: ['system'],
            },
            protocols: [
                {
                    id: '7f158a23-8b65-45ff-aef2-489897a1d762',
                    typeId: 'KNX',
                    type: {
                        id: 'KNX',
                        name: 'KNX',
                    },
                    commInfo: {
                        objs: [
                            {
                                ch: 4,
                                gAddrs: ['0/0/4'],
                                objId: 1,
                            },
                            {
                                ch: 4,
                                gAddrs: ['0/0/8'],
                                objId: 2,
                            },
                        ],
                        pAddr: '1.1.11',
                    },
                },
            ],
            specId: 'c8a54630-ce3a-4102-83b1-acd394e48a8a',
            spec: {
                id: 'c8a54630-ce3a-4102-83b1-acd394e48a8a',
                // manufacturerCode: null,
                switchPanel: null,
                KNX: null,
                RS485: null,
                EnOcean: {
                    EEPCode: null,
                },
            },
            channelInfo: null,
            switchPanelControlInfo: null,
            attrs: [
                {
                    Name_zh_CN: '开关',
                    chId: 4,
                    createdRT: 'oic.r.switch.binary',
                    dpt: '1.001',
                    flags: 148,
                    funId: 'Switch',
                    name: '开关',
                    objId: 1,
                    rt: ['bh.r.attr.actuator'],
                    valueKey: 'value',
                    valueType: 'boolean',
                },
                {
                    Name_zh_CN: '开关',
                    ack4Obj: 1,
                    ackSet: true,
                    chId: 4,
                    createdRT: 'oic.r.switch.binary',
                    dpt: '1.001',
                    flags: 76,
                    funId: 'Switch',
                    name: '开关 状态',
                    objId: 2,
                    rt: ['bh.r.attr.actuator'],
                    valueKey: 'value',
                    valueType: 'boolean',
                },
            ],
            heartbeat: 60,
            sendTelRules: [2],
            imei: '',
            publicIP: '',
            traceIP: '',
            createdBy: 'd07bf909-3157-4cbe-8661-91ba102aa2ea',
            updatedBy: 'd07bf909-3157-4cbe-8661-91ba102aa2ea',
            createdAt: 1630645483935,
            updatedAt: 1630645483937,
        },
        {
            id: 'fe1a5e09-fcbf-4986-8c2a-c54c0be8ec88',
            name: '灯1',
            dvId: 'GOLD-QuLpQpcKEtEt',
            typeId: 265,
            type: {
                id: 265,
                name: 'Light',
                categoryId: 'S',
                category: {
                    id: 'S',
                    name: 'SensorAndGeneralDevice',
                },
            },
            modelId: 'b955d837-7ad4-428e-8611-3600835ae574',
            model: {
                id: 'b955d837-7ad4-428e-8611-3600835ae574',
                name: 'Non',
                brandId: 'ec08a810-8617-49bd-a870-729640d1cbce',
                brand: {
                    id: 'ec08a810-8617-49bd-a870-729640d1cbce',
                    code: 'None',
                    name: 'None',
                },
            },
            projectId: '57eb360a-5897-4f15-8f65-12758d2d16d5',
            spaceId: '59fcadb1-b64e-4a15-af56-1207896bad6b',
            parentId: '4faa9f45-9cfa-4ddf-8c1a-2ef0015a1af0',
            iconId: 'b58f61a7-aff2-403f-a04d-71ab4325cb8c',
            icon: {
                id: 'b58f61a7-aff2-403f-a04d-71ab4325cb8c',
                name: 'ALamp',
                path: 'd-41.png',
                tags: ['system'],
            },
            protocols: [
                {
                    id: 'c97575cc-aa61-4cfa-bb10-a669086e59a7',
                    typeId: 'KNX',
                    type: {
                        id: 'KNX',
                        name: 'KNX',
                    },
                    commInfo: {
                        objs: [
                            {
                                ch: 1,
                                gAddrs: ['0/0/1'],
                                objId: 1,
                            },
                            {
                                ch: 1,
                                gAddrs: ['0/0/5'],
                                objId: 2,
                            },
                        ],
                        pAddr: '1.1.11',
                    },
                },
            ],
            specId: '8bf65dcc-8d0a-4949-9f36-78017dd6ce51',
            spec: {
                id: '8bf65dcc-8d0a-4949-9f36-78017dd6ce51',
                // manufacturerCode: null,
                switchPanel: null,
                KNX: null,
                RS485: null,
                EnOcean: {
                    EEPCode: null,
                },
            },
            channelInfo: null,
            switchPanelControlInfo: null,
            attrs: [
                {
                    Name_zh_CN: '开关',
                    chId: 1,
                    createdRT: 'oic.r.switch.binary',
                    dpt: '1.001',
                    flags: 148,
                    funId: 'Switch',
                    name: '开关',
                    objId: 1,
                    rt: ['bh.r.attr.actuator'],
                    valueKey: 'value',
                    valueType: 'boolean',
                },
                {
                    Name_zh_CN: '开关',
                    ack4Obj: 1,
                    ackSet: true,
                    chId: 1,
                    createdRT: 'oic.r.switch.binary',
                    dpt: '1.001',
                    flags: 76,
                    funId: 'Switch',
                    name: '开关 状态',
                    objId: 2,
                    rt: ['bh.r.attr.actuator'],
                    valueKey: 'value',
                    valueType: 'boolean',
                },
            ],
            heartbeat: 60,
            sendTelRules: [2],
            imei: '',
            publicIP: '',
            traceIP: '',
            createdBy: 'd07bf909-3157-4cbe-8661-91ba102aa2ea',
            updatedBy: 'd07bf909-3157-4cbe-8661-91ba102aa2ea',
            createdAt: 1630645483794,
            updatedAt: 1630645483797,
        },
    ],
};

export {};
