# GET service into
GET {{HOST}}/api/info
accept: application/json

###
POST {{HOST}}/api/login
accept: application/json
Content-Type: application/json

{
  "username": "{{USERNAME}}",
  "password": "{{PASSWORD}}",
  "platformId": {{ELDERWAND_PLANTFORM_ID}}
}

###
