# list devices by project id
GET {{HOST}}/api/devices?projectID={{TARGET_PROJECT_CODE}}&platformID=3
accept: application/json

###


# get the device
#
GET {{HOST}}/api/devices/{{TARGET_DEVICE_ID}}?projectID={{TARGET_PROJECT_CODE}}&platformID=3
accept: application/json
Content-Type: application/json

###

