version: "3"

services:
  elderwand-web:
    container_name: elderwand-web
    image: g13/node:12.19.0-alpine
    build:
      context: ../../.
      dockerfile: docker/web/Dockerfile
    volumes:
      - ../../.:/opt
      - /tmp/elderwand-web/.next:/opt/.next
      - /tmp/elderwand-web/.temp:/opt/.temp
      - /tmp/elderwand-web/node_modules:/opt/node_modules
    # ports:
    #   - "3000:3000"
    env_file:
      - ../../.env.development
    networks:
      - elderwand-network
    # restart: always
    command: "yarn web:dev:install"

networks:
  # default:
  elderwand-network:
    external:
      name: elderwand-network
