version: "3"

services:
  nginx:
    container_name: nginx
    image: rex/nginx:1.19.3-alpine
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl/server.crt:/etc/nginx/ssl.csr
      - ./ssl/server.key:/etc/nginx/ssl.key
      - ./ssl/localhost+5.pem:/etc/nginx/localhost.pem
      - ./ssl/localhost+5-key.pem:/etc/nginx/localhost-key.pem
      - ./index.html:/usr/share/nginx/html/index.html
    ports:
      - "80:80"
      - "443:443"
    networks:
      - elderwand-network
    # network_mode: "host"
    # restart: always
    external_links: 
      - elderwand-web
      - elderwand-api

networks:
  # default:  
  elderwand-network:
    external:
      name: elderwand-network
